export const CREATE_SELLOUTDATA = "CREATE_SELLOUTDATA";
export const RETRIEVE_SELLOUTDATA = "RETRIEVE_SELLOUTDATA";
export const UPDATE_SELLOUTDATA = "UPDATE_SELLOUTDATA";
export const DELETE_SELLOUTDATA = "DELETE_SELLOUTDATA";
export const DELETE_ALL_SELLOUTDATA = "DELETE_ALL_SELLOUTDATA";
export const CREATE_PARTNERDATA = "CREATE_PARTNERDATA";
export const RETRIEVE_PARTNERDATA = "RETRIEVE_PARTNERDATA";
export const RETRIEVE_USERSDATA = "RETRIEVE_USERSDATA";