export const CREATE_SELLOUTDATA = "CREATE_SELLOUTDATA";
export const RETRIEVE_SELLOUTDATA = "RETRIEVE_SELLOUTDATA";
export const UPDATE_SELLOUTDATA = "UPDATE_SELLOUTDATA";
export const DELETE_SELLOUTDATA = "DELETE_SELLOUTDATA";
export const DELETE_ALL_SELLOUTDATA = "DELETE_ALL_SELLOUTDATA";